apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tn-economy-monitor
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tn-economy-monitor
                port:
                  number: 80