import { 
  MetricSummary, 
  PolicyMilestone, 
  SectorContribution, 
  GDPSeriesPoint, 
  EducationEnrolment, 
  InfrastructureIndex, 
  SectorInsight 
} from './types';

// Historical GDP Trends 2004 - 2024
export const gdpHistoricalData: GDPSeriesPoint[] = [
  { year: 2004, tamilNadu: 1.8, averageOthers: 1.2, term: 'A' },
  { year: 2005, tamilNadu: 2.2, averageOthers: 1.4, term: 'A' },
  { year: 2006, tamilNadu: 2.8, averageOthers: 1.8, term: 'A' },
  { year: 2007, tamilNadu: 3.5, averageOthers: 2.1, term: 'A' },
  { year: 2008, tamilNadu: 4.4, averageOthers: 2.6, term: 'A' },
  { year: 2009, tamilNadu: 5.2, averageOthers: 3.2, term: 'A' },
  { year: 2010, tamilNadu: 6.5, averageOthers: 4.1, term: 'A' },
  { year: 2011, tamilNadu: 7.8, averageOthers: 5.1, term: 'B' },
  { year: 2012, tamilNadu: 8.9, averageOthers: 6.0, term: 'B' },
  { year: 2013, tamilNadu: 10.2, averageOthers: 6.9, term: 'B' },
  { year: 2014, tamilNadu: 11.8, averageOthers: 7.8, term: 'B' },
  { year: 2015, tamilNadu: 13.5, averageOthers: 8.8, term: 'B' },
  { year: 2016, tamilNadu: 15.2, averageOthers: 9.8, term: 'B' },
  { year: 2017, tamilNadu: 17.0, averageOthers: 10.9, term: 'B' },
  { year: 2018, tamilNadu: 18.2, averageOthers: 11.5, term: 'B' },
  { year: 2019, tamilNadu: 19.8, averageOthers: 12.4, term: 'B' },
  { year: 2020, tamilNadu: 20.5, averageOthers: 12.1, term: 'B' },
  { year: 2021, tamilNadu: 22.4, averageOthers: 13.5, term: 'C' },
  { year: 2022, tamilNadu: 24.8, averageOthers: 15.2, term: 'C' },
  { year: 2023, tamilNadu: 27.2, averageOthers: 17.1, term: 'C' },
  { year: 2024, tamilNadu: 29.8, averageOthers: 18.9, term: 'C' },
];

// Infrastructure index scores for comparison
export const infrastructureScores: InfrastructureIndex[] = [
  { state: 'TN', score: 80 },
  { state: 'MH', score: 75 },
  { state: 'GJ', score: 70 },
  { state: 'KA', score: 65 },
];

// Higher Education Net Gross Enrolment Ratio (%)
export const educationEnrolmentData: EducationEnrolment[] = [
  { state: 'TN', percentage: 51.4 },
  { state: 'MH', percentage: 34.9 },
  { state: 'KA', percentage: 36.2 },
  { state: 'GJ', percentage: 23.7 },
];

// Sectoral contribution to GSDP
export const defaultSectoralContribution: SectorContribution[] = [
  {
    sector: 'Manufacturing',
    share: 22.4,
    yoyGrowth: 8.2,
    keyDriver: 'Automobiles, Electronics Export',
    iconName: 'precision_manufacturing',
  },
  {
    sector: 'IT & Services',
    share: 34.1,
    yoyGrowth: 11.5,
    keyDriver: 'Software Exports, SaaS Products',
    iconName: 'devices',
  },
  {
    sector: 'Agriculture & Allied',
    share: 11.8,
    yoyGrowth: 3.1,
    keyDriver: 'Horticulture, Deep-sea Fisheries',
    iconName: 'agriculture',
  },
  {
    sector: 'Trade & Hospitality',
    share: 18.5,
    yoyGrowth: 9.4,
    keyDriver: 'Retail Logistics, Domestic Tourism',
    iconName: 'storefront',
  },
];

// Complete repository of insights for all sidebar tabs
export const sectorInsights: Record<string, SectorInsight> = {
  gdp_growth: {
    title: 'Tamil Nadu: State of the Economy',
    subtitle: 'A comprehensive overview of fiscal health, industrial expansion, and socioeconomic indicators. Tamil Nadu continues to demonstrate resilient growth, maintaining its position as one of India\'s leading industrialized states with significant contributions to national GDP and export volumes.',
    summary: 'Executive Summary',
    metrics: [
      {
        id: 'gsdp_growth',
        title: 'GSDP Growth',
        value: '8.2%',
        change: '+1.1% vs National Avg',
        isPositive: true,
        iconName: 'query_stats',
        chartType: 'bar',
        chartData: [40, 55, 45, 70, 90],
      },
      {
        id: 'fdi_inflows',
        title: 'FDI Inflows (Q3)',
        value: '$2.4B',
        change: '+15% YoY',
        isPositive: true,
        iconName: 'account_balance',
        chartType: 'line',
        chartData: [30, 25, 35, 15, 20, 5],
      },
      {
        id: 'iip_index',
        title: 'IIP Index',
        value: '142.8',
        change: 'Stable vs Prev Qtr',
        isPositive: true,
        neutralText: 'Stable vs Prev Qtr',
        iconName: 'factory',
        chartType: 'progress',
        chartData: [75, 60],
      },
    ],
    milestones: [
      {
        id: 'm1',
        years: '2021 - Present',
        title: 'Focus on Advanced Manufacturing & Tech',
        description: 'Implementation of the new EV Policy and establishment of advanced manufacturing hubs. FDI surged significantly in electronics and renewable energy sectors.',
        isActive: true,
      },
      {
        id: 'm2',
        years: '2016 - 2021',
        title: 'Infrastructure & MSME Resilience',
        description: 'Expansion of highway networks and port connectivity. Initiated major MSME credit guarantee schemes to stabilize local industry output during global disruptions.',
        isActive: false,
      },
      {
        id: 'm3',
        years: '2011 - 2016',
        title: 'Vision 2023 Formulated',
        description: 'Strategic blueprint launched focusing on comprehensive infrastructure development and human capital enhancement to drive double-digit growth.',
        isActive: false,
      },
    ],
    contributions: defaultSectoralContribution,
  },
  infrastructure: {
    title: 'Infrastructure & Logistics',
    subtitle: 'Tamil Nadu hosts 4 major shipping ports and has built a dense national highway network. Current priorities concentrate on industrial corridors and integrating off-shore offshore green energy grids to reduce carbon intensity and speed up supply chain routing.',
    summary: 'Logistical Rigor',
    metrics: [
      {
        id: 'highway_span',
        title: 'Highway Length',
        value: '6,840 km',
        change: '+420 km Expanded',
        isPositive: true,
        iconName: 'add_road',
        chartType: 'bar',
        chartData: [50, 60, 65, 80, 95],
      },
      {
        id: 'renewable_cap',
        title: 'Green Grid Capacity',
        value: '18.6 GW',
        change: 'Leading India in Wind',
        isPositive: true,
        iconName: 'wind_power',
        chartType: 'line',
        chartData: [15, 30, 42, 58, 72, 85],
      },
      {
        id: 'port_traffic',
        title: 'Cargo Port Traffic',
        value: '82.1 MT',
        change: '+8.4% YoY',
        isPositive: true,
        iconName: 'sailing',
        chartType: 'progress',
        chartData: [82, 45],
      },
    ],
    milestones: [
      {
        id: 'infra_m1',
        years: '2022 - Present',
        title: 'Tuticorin Green Hydrogen Hub',
        description: 'Initiation of off-shore maritime wind corridors of 5GW and dedicated green hydrogen export terminal frameworks in southern Tamil Nadu.',
        isActive: true,
      },
      {
        id: 'infra_m2',
        years: '2018 - 2022',
        title: 'Chennai-Kanyakumari Industrial Corridor (CKIC)',
        description: 'ADB-funded massive road and power utility upgrade linking coastal districts directly to international shipping nodes.',
        isActive: false,
      },
    ],
  },
  education_skills: {
    title: 'Human Capital & Education',
    subtitle: 'Consistently leading major Indian states in Higher Education Gross Enrolment (GER) at over 50%. The current policy centers on Naan Mudhalvan, providing targeted professional upskilling in AI, semiconductor CAD, and robotics directly to college campuses.',
    summary: 'Skill Leadership',
    metrics: [
      {
        id: 'upskill_cert',
        title: 'Naan Mudhalvan Count',
        value: '1.3M+',
        change: '+14.2% upskilled',
        isPositive: true,
        iconName: 'school',
        chartType: 'bar',
        chartData: [20, 48, 70, 85, 95],
      },
      {
        id: 'rd_centers',
        title: 'Institutional Labs',
        value: '310 hubs',
        change: '+42 state approved',
        isPositive: true,
        iconName: 'science',
        chartType: 'line',
        chartData: [40, 50, 58, 62, 78, 92],
      },
      {
        id: 'ger_ratio',
        title: 'College GER',
        value: '51.4%',
        change: '1st in Major States',
        isPositive: true,
        iconName: 'auto_stories',
        chartType: 'progress',
        chartData: [51, 35],
      },
    ],
    milestones: [
      {
        id: 'edu_m1',
        years: '2022 - Present',
        title: 'Naan Mudhalvan Upskilling Initiative',
        description: 'Mandated industry-vetted courses for engineering and science graduates in Web3, VLSI desig, and analytics. Over 1.3 million youth trained with direct corporate linkages.',
        isActive: true,
      },
      {
        id: 'edu_m2',
        years: '2019 - 2021',
        title: 'Model Schools & STEM Labs',
        description: 'Established smart schools and specialized robotic design laboratories across governmental high schools to prime young talent for industrial careers.',
        isActive: false,
      },
    ],
  },
  public_health: {
    title: 'Public Health Care Systems',
    subtitle: 'Known as the healthcare capital of South Asia. Tamil Nadu combines standard rural primary outreach with highly sophisticated urban tertiary clusters, rendering medical tourism and affordable public treatment highly accessible.',
    summary: 'Universal Health',
    metrics: [
      {
        id: 'med_tourism',
        title: 'Medical Tourism Inflows',
        value: '$620M',
        change: '+18.5% YoY',
        isPositive: true,
        iconName: 'medical_services',
        chartType: 'bar',
        chartData: [32, 45, 50, 68, 88],
      },
      {
        id: 'phc_coverage',
        title: 'Active Rural PHCs',
        value: '2,143',
        change: '98% Quality Graded',
        isPositive: true,
        iconName: 'home_health',
        chartType: 'line',
        chartData: [60, 65, 78, 80, 89, 98],
      },
      {
        id: 'infant_mortality',
        title: 'Infant Mortality Rate',
        value: '13/1000',
        change: 'Reduced (Ideal Goal < 10)',
        isPositive: true,
        iconName: 'child_care',
        chartType: 'progress',
        chartData: [87, 60],
      },
    ],
    milestones: [
      {
        id: 'health_m1',
        years: '2021 - Present',
        title: 'Makkalai Thedi Maruthuvam (Healthcare at Doorstep)',
        description: 'Statewide program diagnosing and dispersing chronic disease prescriptions directly to rural dwellings, cutting outtravel expenditures for the elderly.',
        isActive: true,
      },
      {
        id: 'health_m2',
        years: '2017 - 2021',
        title: 'Universal Health Insurance Expansion',
        description: 'Integrating remote health-subcenters to state coverages, providing cash-free coverage up to ₹5 Lakhs per family.',
        isActive: false,
      },
    ],
  },
  industrial_output: {
    title: 'Industrial Output & Advanced Manufacturing',
    subtitle: 'Referred to as the "Detroit of South Asia" due to automobile production. The region is transitioning rapidly to Electric Vehicles (EV), battery factories, SaaS technology design, and electronic semiconductor assembly.',
    summary: 'Detroit of South Asia',
    metrics: [
      {
        id: 'ev_share',
        title: 'EV Production Share',
        value: '35%',
        change: 'Highest in India',
        isPositive: true,
        iconName: 'electric_car',
        chartType: 'bar',
        chartData: [10, 22, 48, 75, 95],
      },
      {
        id: 'elec_exports',
        title: 'Electronics Export v3',
        value: '$9.5B',
        change: 'Ranked #1 State',
        isPositive: true,
        iconName: 'memory',
        chartType: 'line',
        chartData: [15, 23, 38, 52, 74, 95],
      },
      {
        id: 'textile_hub',
        title: 'Textile Index Hub',
        value: '148.5',
        change: '+4.2% Growth',
        isPositive: true,
        iconName: 'checkroom',
        chartType: 'progress',
        chartData: [78, 65],
      },
    ],
    milestones: [
      {
        id: 'ind_m1',
        years: '2023 - Present',
        title: 'Tamil Nadu EV Policy 2023',
        description: 'Road tax exemptions, capital subsidies up to 20% for battery Gigafactories, and transition assistance for ICE automotive component suppliers.',
        isActive: true,
      },
      {
        id: 'ind_m2',
        years: '2020 - 2023',
        title: 'Tech Park and Electronics Assembly Hubs',
        description: 'Massive multi-billion investments from global manufacturers (Foxconn, Pegatron, Tata Electronics) in Krishnagiri and Sriperumbudur.',
        isActive: false,
      },
    ],
  },
};
